name: TraceurMW
spring:
  security:
    user:
      password: admin
      name: admin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mw?serverTimezone=UTC
    username: root
    password: root
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
server:
  port: 6689

